name: First Workflow
on: 
  push

jobs:
  first-job:
    name: "firs job"
    runs-on: ubuntu-latest
    steps:
      - name: before checkout
        run: ls
        shell: bash

      - name: check out steps 
        uses:  actions/checkout@v4

      - name: after checkout
        run: ls
        shell: bash