name: First Workflow
on: 
  push

jobs:
  first-job:
    name: "firs job"
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
